[package]
name = "yaros"
version = "0.1.0"
edition = "2021"
default-run = "kernel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "kernel"
path = "src/main.rs"
test = true