name: Setup
description: Configure build environment inside CI container

runs:
  using: composite
  steps:
    - name: Setup build environment
      shell: bash
      run: |
        ln -sf "$LINUX_HEADERS_PATH" headers/linux_headers
        ln -sf "$MUSL_HEADERS_PATH" headers/musl_headers
        mkdir -p kernel/compiled_userspace_nix
