FROM nixos/nix:latest

RUN mkdir -p /etc/nix && \
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

COPY flake.nix flake.lock rust-toolchain /workspace/

WORKDIR /workspace

RUN nix develop .#ci --profile /nix-profile --command true

RUN git config --global --add safe.directory '*'
