FROM nixos/nix:latest

RUN mkdir -p /etc/nix && \
    echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

# Install Node.js (required by GitHub Actions for checkout and other JS actions)
RUN nix-env -iA nixpkgs.nodejs

COPY flake.nix flake.lock rust-toolchain /workspace/

WORKDIR /workspace

RUN nix develop .#ci --profile /nix-profile --command true

RUN git config --global --add safe.directory '*'
