build: build-cargo patch-symbols

patch-symbols:
    riscv64-unknown-linux-musl-nm --demangle --numeric-sort --line-numbers target/riscv64gc-unknown-none-elf/release/kernel | grep -e ' t ' -e ' T ' > symbols && printf '\0' >> symbols
    riscv64-unknown-linux-musl-objcopy --update-section symbols=./symbols target/riscv64gc-unknown-none-elf/release/kernel

build-cargo: build-userspace
    cargo build --release

build-userspace:
    cd userspace && cargo build --bins --target-dir ../target-userspace --artifact-dir ../kernel/compiled_userspace -Z unstable-options --release # -Z build-std=panic_abort,std

clippy: build-userspace
    cd userspace && cargo clippy -- -D warnings
    cargo clippy -- -D warnings
    cargo clippy --manifest-path system-tests/Cargo.toml --target x86_64-unknown-linux-gnu --no-deps -- -D warnings
    cargo clippy --manifest-path mcp-server/Cargo.toml --target x86_64-unknown-linux-gnu --no-deps -- -D warnings
    cargo clippy --tests

clean:
    rm -f kernel/compiled_userspace/*
    rm -f kernel/src/autogenerated/userspace_programs.rs
    rm -rf target-userspace
    cargo clean

debugReleaseCommand := 'cargo run --release -- --wait'
gdb := 'pwndbg --nh -iex "add-auto-load-safe-path ."'

run: build
    cargo run --release

test: unit-test system-test

ci: build
    @echo "Running CI checks..."
    @echo "==> Clippy"
    just clippy
    @echo "==> Format check"
    cargo fmt --check
    @echo "==> Unit tests"
    just unit-test
    @echo "==> Miri"
    just miri
    @echo "==> System tests"
    just system-test
    @echo "All CI checks passed!"

unit-test: build-userspace
    cargo test --release

system-test: build
    cargo nextest run --release --manifest-path system-tests/Cargo.toml --target x86_64-unknown-linux-gnu

stress-system-test: build
    for i in $(seq 1 5); do echo "==> Stress run $i/5"; cargo nextest run --release --manifest-path system-tests/Cargo.toml --target x86_64-unknown-linux-gnu || exit 1; done

loop-system-test TEST: build
    while true; do cargo nextest run --release --manifest-path system-tests/Cargo.toml --target x86_64-unknown-linux-gnu {{TEST}} || break; done

deadlock-hunt: build
    #!/usr/bin/env bash
    i=0; while true; do i=$((i+1)); echo "==> Deadlock hunt iteration $i at $(date)"; SOLAYA_ENABLE_GDB=1 cargo nextest run --release --manifest-path system-tests/Cargo.toml --target x86_64-unknown-linux-gnu --profile deadlock-hunt || break; done

miri: build-cargo
    MIRIFLAGS="-Zmiri-env-forward=RUST_BACKTRACE -Zmiri-strict-provenance" RUST_BACKTRACE=1 cargo miri test --target riscv64gc-unknown-linux-gnu

mcp-server:
    cargo build --release --manifest-path mcp-server/Cargo.toml --target x86_64-unknown-linux-gnu

fetch-deps:
    cargo fetch
    cargo fetch --manifest-path ./system-tests/Cargo.toml
    cargo fetch --manifest-path ./mcp-server/Cargo.toml

attach:
    @test -f .gdb-port || { echo "Error: .gdb-port not found. Is QEMU running with --gdb?"; exit 1; }
    {{gdb}} -ex "target remote :$(cat .gdb-port)" $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel

debug: build
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -v 'while [ ! -f .gdb-port ]; do sleep 0.1; done; {{gdb}} -ex "target remote :$(cat .gdb-port)" $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel' \; attach

debugf FUNC: build
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -v 'while [ ! -f .gdb-port ]; do sleep 0.1; done; {{gdb}} -ex "target remote :$(cat .gdb-port)" -ex "hbreak {{FUNC}}" -ex "c" $(pwd)/target/riscv64gc-unknown-none-elf/release/kernel' \; attach

debuguf BIN FUNC: build
    tmux new-session -d '{{debugReleaseCommand}}' \; split-window -v 'while [ ! -f .gdb-port ]; do sleep 0.1; done; {{gdb}} -ex "target remote :$(cat .gdb-port)" -ex "hbreak {{FUNC}}" -ex "c" $(pwd)/kernel/compiled_userspace/{{BIN}}' \; attach

disassm: build
    riscv64-unknown-linux-musl-objdump -d --demangle --disassembler-color=on visualize-jumps=extended-color target/riscv64gc-unknown-none-elf/release/kernel

addr2line ADDR:
    riscv64-unknown-linux-musl-addr2line -f -p -i -C -e target/riscv64gc-unknown-none-elf/release/kernel {{ADDR}}
