[build]
target = "riscv64gc-unknown-linux-musl"
# Leave it here in case we need it in the future
# Or just if we forget and get here by accident to remember
rustflags = ["-Ctarget-feature=+relax"]

[target.riscv64gc-unknown-linux-musl]
linker = "musl-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
linker = "gcc"
