use alloc::{string::String, sync::Arc, vec::Vec};
use headers::errno::Errno;

use crate::{
    autogenerated::userspace_programs::PROGRAMS,
    klibc::{consumable_buffer::ConsumableBuffer, elf::ElfFile},
    processes::{loader, process::Process, userspace_ptr::UserspacePtr},
};
use common::syscalls::trap_frame::{Register, TrapFrame};

use super::linux::LinuxSyscallHandler;

impl LinuxSyscallHandler {
    pub(super) fn do_execve(&mut self, filename: usize, argv: usize) -> Result<isize, Errno> {
        let process = self.effective_process();
        let filename_bytes = process.with_lock(|p| {
            let ptr = UserspacePtr::new(filename as *const u8);
            p.read_userspace_slice(&ptr, 256)
        })?;
        let mut buf = ConsumableBuffer::new(&filename_bytes);
        let filename_str = buf.consume_str().ok_or(Errno::EFAULT)?;
        let name = filename_str.strip_prefix('/').unwrap_or(filename_str);

        let mut args: Vec<&str> = Vec::new();
        let argv_ptrs = process.with_lock(|p| {
            let ptr = UserspacePtr::new(argv as *const usize);
            p.read_userspace_slice(&ptr, 32)
        })?;

        // Skip argv[0] (program name) since load_elf adds it automatically
        let mut arg_buffers: Vec<Vec<u8>> = Vec::new();
        let mut first = true;
        for &arg_ptr in &argv_ptrs {
            if arg_ptr == 0 {
                break;
            }
            if first {
                first = false;
                continue;
            }
            let arg_bytes = process.with_lock(|p| {
                let ptr = UserspacePtr::new(arg_ptr as *const u8);
                p.read_userspace_slice(&ptr, 256)
            })?;
            arg_buffers.push(arg_bytes);
        }
        for buf_ref in &arg_buffers {
            let mut cb = ConsumableBuffer::new(buf_ref);
            if let Some(s) = cb.consume_str() {
                args.push(s);
            }
        }

        let elf_data = PROGRAMS
            .iter()
            .find(|(prog_name, _)| *prog_name == name)
            .map(|(_, data)| *data)
            .ok_or(Errno::ENOENT)?;

        let elf = ElfFile::parse(elf_data).expect("Cannot parse ELF file");
        let loaded = loader::load_elf(&elf, name, &args).expect("ELF loading must succeed");

        let process_name = Arc::new(String::from(name));
        let old_process = self.effective_process();
        let (old_pgid, old_sid, old_cwd) =
            old_process.with_lock(|p| (p.pgid(), p.sid(), String::from(p.cwd())));
        let new_process = Arc::new(crate::klibc::Spinlock::new(Process::new(
            process_name.clone(),
            loaded.page_tables,
            loaded.allocated_pages,
            loaded.brk,
            self.current_thread.lock().get_tid(),
            old_pgid,
            old_sid,
        )));

        let mut inherited_fd_table = self.effective_process().with_lock(|p| p.fd_table().clone());
        inherited_fd_table.close_cloexec_fds();
        {
            let mut np = new_process.lock();
            np.set_fd_table(inherited_fd_table);
            np.set_cwd(old_cwd);
        }

        let current_thread = self.current_thread.clone();
        let old_process = current_thread.lock().process();
        let tid = current_thread.lock().get_tid();

        old_process.lock().remove_thread(tid);

        current_thread.with_lock(|mut t| {
            t.set_process(new_process.clone(), process_name);
            let mut regs = TrapFrame::zero();
            regs[Register::a0] = loaded.args_start.as_usize();
            regs[Register::sp] = loaded.args_start.as_usize();
            t.set_register_state(regs);
            t.set_program_counter(loaded.entry_address);
            t.set_registers_replaced(true);

            if let Some(vfork_state) = t.take_vfork_state() {
                vfork_state.lock().wake();
            }
        });

        new_process
            .lock()
            .add_thread(tid, Arc::downgrade(&current_thread));

        Ok(0)
    }
}
