use crate::{
    autogenerated::userspace_programs::PROGRAMS,
    cpu::Cpu,
    debug, fs,
    io::pipe,
    klibc::{
        consumable_buffer::ConsumableBuffer,
        elf::ElfFile,
        util::{ByteInterpretable, UsizeExt},
    },
    memory::{PAGE_SIZE, VirtAddr, page::Pages, page_tables::XWRMode},
    net::{self, arp, sockets::Port, udp::UdpHeader},
    print, println,
    processes::{
        brk::Brk,
        fd_table::{FdFlags, FileDescriptor},
        futex::{self, FutexWait},
        loader,
        process::{Process, ProcessRef},
        process_table,
        thread::{Thread, ThreadRef, VforkState, VforkWait, get_next_tid},
        timer,
        userspace_ptr::UserspacePtr,
        wait_child::{WaitChild, WaitPid},
    },
    syscalls::macros::linux_syscalls,
};
use alloc::{string::String, sync::Arc, vec, vec::Vec};
use common::{
    ioctl::{ARPHRD_ETHER, Ifreq, SIOCGIFHWADDR, SIOCSIFADDR, SOLAYA_LIST_PROGRAMS, SOLAYA_PANIC},
    pid::Tid,
    syscalls::trap_frame::{Register, TrapFrame},
};
use core::ffi::{c_int, c_uint, c_ulong};
use headers::{
    errno::Errno,
    socket::{AF_INET, SOCK_CLOEXEC, SOCK_DGRAM, sockaddr_in},
    syscall_types::{
        _NSIG, CLOCK_MONOTONIC, CLOCK_REALTIME, CLONE_CHILD_CLEARTID, CLONE_PARENT_SETTID,
        CLONE_SETTLS, CLONE_THREAD, CLONE_VFORK, CLONE_VM, F_GETFL, F_SETFL, FIONBIO,
        FUTEX_PRIVATE_FLAG, FUTEX_WAIT, FUTEX_WAKE, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, O_CREAT,
        O_DIRECTORY, O_TRUNC, PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE, SIG_BLOCK, SIG_SETMASK,
        SIG_UNBLOCK, SIGCHLD, SIGKILL, SIGSTOP, TIOCGWINSZ, iovec, pollfd, sigaction, sigset_t,
        stack_t, timespec,
    },
};

impl ByteInterpretable for sockaddr_in {}
impl ByteInterpretable for headers::fs::stat {}
impl ByteInterpretable for headers::fs::statx {}

linux_syscalls! {
    SYSCALL_NR_BIND => bind(fd: c_int, addr: *const u8, addrlen: c_uint);
    SYSCALL_NR_BRK => brk(brk: c_ulong);
    SYSCALL_NR_CLONE => clone(flags: c_ulong, stack: usize, ptid: Option<*mut c_int>, tls: c_ulong, ctid: Option<*mut c_int>);
    SYSCALL_NR_CLOSE => close(fd: c_int);
    SYSCALL_NR_DUP3 => dup3(oldfd: c_int, newfd: c_int, flags: c_int);
    SYSCALL_NR_EXECVE => execve(filename: usize, argv: usize, envp: usize);
    SYSCALL_NR_EXIT => exit(status: c_int);
    SYSCALL_NR_EXIT_GROUP => exit_group(status: c_int);
    SYSCALL_NR_FACCESSAT => faccessat(dirfd: c_int, pathname: *const u8, mode: c_int);
    SYSCALL_NR_FADVISE64 => fadvise64(fd: c_int, offset: isize, len: isize, advice: c_int);
    SYSCALL_NR_FCNTL => fcntl(fd: c_int, cmd: c_int, arg: c_ulong);
    SYSCALL_NR_FSTAT => fstat(fd: c_int, statbuf: *mut u8);
    SYSCALL_NR_FUTEX => futex(uaddr: usize, op: c_int, val: c_uint, timeout: usize, uaddr2: usize, val3: c_uint);
    SYSCALL_NR_GETCWD => getcwd(buf: *mut u8, size: usize);
    SYSCALL_NR_GETDENTS64 => getdents64(fd: c_int, dirp: *mut u8, count: usize);
    SYSCALL_NR_GETEGID => getegid();
    SYSCALL_NR_GETEUID => geteuid();
    SYSCALL_NR_GETGID => getgid();
    SYSCALL_NR_GETPGID => getpgid(pid: c_int);
    SYSCALL_NR_GETPID => getpid();
    SYSCALL_NR_GETPPID => getppid();
    SYSCALL_NR_GETSID => getsid(pid: c_int);
    SYSCALL_NR_GETTID => gettid();
    SYSCALL_NR_GETUID => getuid();
    SYSCALL_NR_IOCTL => ioctl(fd: c_int, op: c_uint, arg: usize);
    SYSCALL_NR_LLISTXATTR => llistxattr(pathname: *const u8, list: *mut u8, size: usize);
    SYSCALL_NR_LSEEK => lseek(fd: c_int, offset: isize, whence: c_int);
    SYSCALL_NR_MADVISE => madvise(addr: usize, length: usize, advice: c_int);
    SYSCALL_NR_MKDIRAT => mkdirat(dirfd: c_int, pathname: *const u8, mode: c_uint);
    SYSCALL_NR_MMAP => mmap(addr: usize, length: usize, prot: c_uint, flags: c_uint, fd: c_int, offset: isize);
    SYSCALL_NR_MPROTECT => mprotect(addr: usize, len: usize, prot: c_int);
    SYSCALL_NR_MUNMAP => munmap(addr: usize, length: usize);
    SYSCALL_NR_CLOCK_GETTIME => clock_gettime(clockid: c_int, tp: *mut timespec);
    SYSCALL_NR_CLOCK_NANOSLEEP => clock_nanosleep(clockid: c_int, flags: c_int, request: *const timespec, remain: Option<*mut timespec>);
    SYSCALL_NR_NANOSLEEP => nanosleep(duration: *const timespec, rem: Option<*const timespec>);
    SYSCALL_NR_NEWFSTATAT => newfstatat(dirfd: c_int, pathname: *const u8, statbuf: *mut u8, flags: c_int);
    SYSCALL_NR_OPENAT => openat(dirfd: c_int, pathname: *const u8, flags: c_int, mode: c_uint);
    SYSCALL_NR_PIPE2 => pipe2(fds: *mut c_int, flags: c_int);
    SYSCALL_NR_PPOLL => ppoll(fds: *mut pollfd, n: c_uint, to: Option<*const timespec>, mask: Option<*const sigset_t>);
    SYSCALL_NR_PRCTL => prctl();
    SYSCALL_NR_READ => read(fd: c_int, buf: *mut u8, count: usize);
    SYSCALL_NR_READLINKAT => readlinkat(dirfd: c_int, pathname: *const u8, buf: *mut u8, bufsiz: usize);
    SYSCALL_NR_RECVFROM => recvfrom(fd: c_int, buf: *mut u8, len: usize, flags: c_int, src_addr: Option<*mut u8>, addrlen: Option<*mut c_uint>);
    SYSCALL_NR_RT_SIGACTION => rt_sigaction(sig: c_uint, act: Option<*const sigaction>, oact: Option<*mut sigaction>, sigsetsize: usize);
    SYSCALL_NR_RT_SIGPROCMASK => rt_sigprocmask(how: c_uint, set: Option<*const sigset_t>, oldset: Option<*mut sigset_t>, sigsetsize: usize);
    SYSCALL_NR_RT_SIGRETURN => rt_sigreturn();
    SYSCALL_NR_SENDTO => sendto(fd: c_int, buf: *const u8, len: usize, flags: c_int, dest_addr: *const u8, addrlen: c_uint);
    SYSCALL_NR_SETPGID => setpgid(pid: c_int, pgid: c_int);
    SYSCALL_NR_SETSID => setsid();
    SYSCALL_NR_SET_ROBUST_LIST => set_robust_list(head: usize, len: usize);
    SYSCALL_NR_SET_TID_ADDRESS => set_tid_address(tidptr: *mut c_int);
    SYSCALL_NR_SIGALTSTACK => sigaltstack(uss: Option<*const stack_t>, uoss: Option<*mut stack_t>);
    SYSCALL_NR_SOCKET => socket(domain: c_int, typ: c_int, protocol: c_int);
    SYSCALL_NR_STATX => statx(dirfd: c_int, pathname: *const u8, flags: c_int, mask: c_uint, statxbuf: *mut u8);
    SYSCALL_NR_KILL => kill(pid: c_int, sig: c_int);
    SYSCALL_NR_TGKILL => tgkill(tgid: c_int, tid: c_int, sig: c_int);
    SYSCALL_NR_TKILL => tkill(tid: c_int, sig: c_int);
    SYSCALL_NR_UMASK => umask(mask: c_uint);
    SYSCALL_NR_UNLINKAT => unlinkat(dirfd: c_int, pathname: *const u8, flags: c_int);
    SYSCALL_NR_UTIMENSAT => utimensat(dirfd: c_int, pathname: *const u8, times: usize, flags: c_int);
    SYSCALL_NR_WAIT4 => wait4(pid: c_int, status: Option<*mut c_int>, options: c_int, rusage: usize);
    SYSCALL_NR_WRITEV => writev(fd: c_int, iov: *const iovec, iovcnt: c_int);
    SYSCALL_NR_WRITE => write(fd: c_int, buf: *const u8, count: usize);
}

pub struct LinuxSyscallHandler {
    current_process: ProcessRef,
    current_thread: ThreadRef,
    current_tid: Tid,
}

impl LinuxSyscalls for LinuxSyscallHandler {
    async fn read(
        &mut self,
        fd: c_int,
        buf: LinuxUserspaceArg<*mut u8>,
        count: usize,
    ) -> Result<isize, headers::errno::Errno> {
        let (descriptor, flags) = self
            .current_process
            .with_lock(|p| {
                p.fd_table()
                    .get(fd)
                    .map(|e| (e.descriptor.clone(), e.flags))
            })
            .ok_or(Errno::EBADF)?;

        let data = if flags.is_nonblocking() {
            descriptor.try_read(count)?
        } else {
            descriptor.read(count).await?
        };
        assert!(data.len() <= count, "Read more than requested");
        buf.write_slice(&data)?;

        Ok(data.len() as isize)
    }

    async fn write(
        &mut self,
        fd: i32,
        buf: LinuxUserspaceArg<*const u8>,
        count: usize,
    ) -> Result<isize, Errno> {
        let descriptor = self
            .current_process
            .with_lock(|p| p.fd_table().get(fd).map(|e| e.descriptor.clone()))
            .ok_or(Errno::EBADF)?;

        let data = buf.validate_slice(count)?;
        descriptor.write(&data)?;

        Ok(count as isize)
    }

    async fn exit(&mut self, status: c_int) -> Result<isize, Errno> {
        let exit_status = crate::processes::signal::ExitStatus::Exited(status.to_le_bytes()[0]);
        Cpu::with_scheduler(|mut s| {
            s.kill_current_thread(exit_status);
        });
        debug!("Exit thread with status: {status}\n");
        Ok(0)
    }

    async fn exit_group(&mut self, status: c_int) -> Result<isize, Errno> {
        let exit_status = crate::processes::signal::ExitStatus::Exited(status.to_le_bytes()[0]);
        Cpu::with_scheduler(|mut s| {
            s.kill_current_process(exit_status);
        });

        debug!("Exit process with status: {status}\n");
        Ok(0)
    }

    async fn set_robust_list(&mut self, _head: usize, _len: usize) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn set_tid_address(
        &mut self,
        tidptr: LinuxUserspaceArg<*mut c_int>,
    ) -> Result<isize, Errno> {
        self.current_thread.with_lock(|mut t| {
            t.set_clear_child_tid((&tidptr).into());
        });
        Ok(self.current_tid.as_isize())
    }

    async fn ppoll(
        &mut self,
        fds: LinuxUserspaceArg<*mut pollfd>,
        n: c_uint,
        to: LinuxUserspaceArg<Option<*const timespec>>,
        mask: LinuxUserspaceArg<Option<*const sigset_t>>,
    ) -> Result<isize, Errno> {
        let mask = mask.validate_ptr()?;

        let old_mask = if let Some(mask) = mask {
            Some(self.current_thread.with_lock(|mut t| t.set_sigset(mask)))
        } else {
            None
        };

        Self::validate_poll_timeout(to.validate_ptr()?);

        let poll_fds = fds.validate_slice(n as usize)?;
        for pfd in &poll_fds {
            self.current_process
                .with_lock(|p| p.fd_table().get(pfd.fd).map(|e| e.descriptor.clone()))
                .ok_or(Errno::EBADF)?;
            assert_eq!(
                pfd.events, 0,
                "No further events are supported at the moment"
            );
        }

        if let Some(mask) = old_mask {
            self.current_thread.with_lock(|mut t| t.set_sigset(mask));
        }

        Ok(0)
    }

    async fn rt_sigaction(
        &mut self,
        sig: c_uint,
        act: LinuxUserspaceArg<Option<*const sigaction>>,
        oact: LinuxUserspaceArg<Option<*mut sigaction>>,
        sigsetsize: usize,
    ) -> Result<isize, Errno> {
        if sigsetsize != core::mem::size_of::<sigset_t>()
            || matches!(sig, SIGKILL | SIGSTOP)
            || sig >= _NSIG
        {
            return Err(Errno::EINVAL);
        }

        let old_act = if let Some(act) = act.validate_ptr()? {
            self.current_thread
                .with_lock(|mut t| t.set_sigaction(sig, act))
        } else {
            self.current_thread.with_lock(|t| t.get_sigaction(sig))
        }?;

        oact.write_if_not_none(old_act)?;

        Ok(0)
    }

    async fn rt_sigprocmask(
        &mut self,
        how: c_uint,
        set: LinuxUserspaceArg<Option<*const sigset_t>>,
        oldset: LinuxUserspaceArg<Option<*mut sigset_t>>,
        sigsetsize: usize,
    ) -> Result<isize, Errno> {
        if sigsetsize != core::mem::size_of::<sigset_t>() {
            return Err(Errno::EINVAL);
        }

        let new_set = set.validate_ptr()?;

        let old_set_in_thread = if let Some(new_set) = new_set {
            self.current_thread.with_lock(|mut t| {
                let mut current_set = t.get_sigset();
                match how {
                    SIG_BLOCK => current_set.sig[0] |= new_set.sig[0],
                    SIG_UNBLOCK => current_set.sig[0] &= !new_set.sig[0],
                    SIG_SETMASK => current_set.sig[0] = new_set.sig[0],
                    _ => {
                        return Err(Errno::EINVAL);
                    }
                }
                Ok(t.set_sigset(current_set))
            })?
        } else {
            self.current_thread.with_lock(|t| t.get_sigset())
        };

        oldset.write_if_not_none(old_set_in_thread)?;

        Ok(0)
    }

    async fn rt_sigreturn(&mut self) -> Result<isize, Errno> {
        self.current_thread.with_lock(|mut t| {
            crate::processes::signal::restore_signal_frame(&mut t)?;
            t.set_registers_replaced(true);
            Ok::<_, Errno>(())
        })?;
        Ok(0)
    }

    async fn sigaltstack(
        &mut self,
        uss: LinuxUserspaceArg<Option<*const stack_t>>,
        uoss: LinuxUserspaceArg<Option<*mut stack_t>>,
    ) -> Result<isize, Errno> {
        let uss = uss.validate_ptr()?;
        self.current_thread.with_lock(|mut t| {
            let old = t.get_sigaltstack();
            if let Some(uss) = uss {
                t.set_sigaltstack(&uss);
            }
            uoss.write_if_not_none(old)?;
            Ok::<(), Errno>(())
        })?;
        Ok(0)
    }

    fn get_process(&self) -> ProcessRef {
        let process = self.current_process.clone();
        let vfork_parent = process.lock().vfork_parent().cloned();
        vfork_parent.unwrap_or(process)
    }

    async fn nanosleep(
        &mut self,
        duration: LinuxUserspaceArg<*const timespec>,
        _rem: LinuxUserspaceArg<Option<*const timespec>>,
    ) -> Result<isize, Errno> {
        let duration = duration.validate_ptr()?;
        if duration.tv_sec < 0 || !(0..=999999999).contains(&duration.tv_nsec) {
            return Err(Errno::EINVAL);
        }
        timer::sleep(&duration)?.await;
        Ok(0)
    }

    async fn clock_nanosleep(
        &mut self,
        clockid: c_int,
        flags: c_int,
        request: LinuxUserspaceArg<*const timespec>,
        _remain: LinuxUserspaceArg<Option<*mut timespec>>,
    ) -> Result<isize, Errno> {
        assert!(
            clockid == CLOCK_MONOTONIC as c_int || clockid == CLOCK_REALTIME as c_int,
            "clock_nanosleep: unsupported clockid {clockid}"
        );
        assert!(flags == 0, "clock_nanosleep: unsupported flags {flags}");
        let duration = request.validate_ptr()?;
        if duration.tv_sec < 0 || !(0..=999999999).contains(&duration.tv_nsec) {
            return Err(Errno::EINVAL);
        }
        timer::sleep(&duration)?.await;
        Ok(0)
    }

    async fn brk(&mut self, brk: c_ulong) -> Result<isize, headers::errno::Errno> {
        self.current_process.with_lock(|mut p| {
            Ok(p.brk(crate::memory::VirtAddr::new(brk.as_usize()))
                .as_usize() as isize)
        })
    }

    async fn mmap(
        &mut self,
        addr: usize,
        length: usize,
        prot: c_uint,
        flags: c_uint,
        fd: c_int,
        offset: isize,
    ) -> Result<isize, headers::errno::Errno> {
        assert_eq!(
            flags & !(MAP_ANONYMOUS | MAP_PRIVATE | MAP_FIXED),
            0,
            "Only this flags are implemented so far."
        );
        assert_eq!(
            flags & (MAP_ANONYMOUS | MAP_PRIVATE),
            MAP_ANONYMOUS | MAP_PRIVATE,
            "File backed mappings and shared mappings are not supported yet."
        );
        assert_eq!(fd, -1, "fd must be -1 when working in MAP_ANONYMOUS");
        assert_eq!(
            offset, 0,
            "offset must be null when working with MAP_ANONYMOUS"
        );
        if length == 0 {
            return Err(Errno::EINVAL);
        }
        let length = length.next_multiple_of(PAGE_SIZE);
        if (flags & MAP_FIXED) > 0 && addr == 0 {
            return Err(Errno::EINVAL);
        }
        let permission = match prot {
            PROT_NONE => XWRMode::ReadOnly,
            PROT_EXEC => XWRMode::ExecuteOnly,
            PROT_READ => XWRMode::ReadOnly,
            x if x == (PROT_READ | PROT_WRITE) => XWRMode::ReadWrite,
            _ => return Err(Errno::EINVAL),
        };
        self.current_process.with_lock(|mut p| {
            if (flags & MAP_FIXED) > 0 {
                // Only handles exact overlap (full range already mapped). Partial overlap
                // is not handled -- the real MAP_FIXED semantic would unmap existing pages
                // first. Sufficient for musl, which only re-maps exact prior allocations.
                if p.get_page_table()
                    .is_mapped(VirtAddr::new(addr)..VirtAddr::new(addr + length))
                {
                    p.get_page_table_mut()
                        .mprotect(VirtAddr::new(addr), length, permission);
                    return Ok(addr as isize);
                }
                let ptr = p.mmap_pages_with_address(
                    Pages::new(length / PAGE_SIZE),
                    VirtAddr::new(addr),
                    permission,
                );
                return Ok(ptr as isize);
            }
            if addr == 0
                || p.get_page_table()
                    .is_mapped(VirtAddr::new(addr)..VirtAddr::new(addr + length))
            {
                return Ok(p.mmap_pages(Pages::new(length / PAGE_SIZE), permission) as isize);
            }
            Ok(p.mmap_pages_with_address(
                Pages::new(length / PAGE_SIZE),
                VirtAddr::new(addr),
                permission,
            ) as isize)
        })
    }

    async fn madvise(
        &mut self,
        _addr: usize,
        _length: usize,
        _advice: c_int,
    ) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn mprotect(&mut self, addr: usize, len: usize, prot: c_int) -> Result<isize, Errno> {
        if !addr.is_multiple_of(PAGE_SIZE) || len == 0 {
            return Err(Errno::EINVAL);
        }
        let prot = c_uint::try_from(prot).map_err(|_| Errno::EINVAL)?;
        let size = len.next_multiple_of(PAGE_SIZE);
        let mode = match prot {
            PROT_NONE => XWRMode::ReadOnly,
            PROT_READ => XWRMode::ReadOnly,
            PROT_EXEC => XWRMode::ExecuteOnly,
            x if x == (PROT_READ | PROT_WRITE) => XWRMode::ReadWrite,
            x if x == (PROT_READ | PROT_EXEC) => XWRMode::ReadExecute,
            x if x == (PROT_READ | PROT_WRITE | PROT_EXEC) => XWRMode::ReadWriteExecute,
            _ => return Err(Errno::EINVAL),
        };
        self.current_process.with_lock(|mut p| {
            p.get_page_table_mut()
                .mprotect(VirtAddr::new(addr), size, mode);
        });
        Ok(0)
    }

    async fn munmap(&mut self, addr: usize, length: usize) -> Result<isize, headers::errno::Errno> {
        if !addr.is_multiple_of(PAGE_SIZE) || length == 0 {
            return Err(Errno::EINVAL);
        }
        self.current_process
            .with_lock(|mut p| p.munmap_pages(VirtAddr::new(addr), length))?;
        Ok(0)
    }

    async fn prctl(&mut self) -> Result<isize, headers::errno::Errno> {
        // We dont support any of prctl right now
        Err(Errno::EINVAL)
    }

    async fn ioctl(
        &mut self,
        fd: c_int,
        op: c_uint,
        arg: usize,
    ) -> Result<isize, headers::errno::Errno> {
        let descriptor = self
            .current_process
            .with_lock(|p| p.fd_table().get(fd).map(|e| e.descriptor.clone()))
            .ok_or(Errno::EBADF)?;

        match descriptor {
            FileDescriptor::Stdout | FileDescriptor::Stderr if op == TIOCGWINSZ => {
                Err(Errno::ENOTTY)
            }
            FileDescriptor::Stdout if op == SOLAYA_LIST_PROGRAMS => {
                for (name, _) in PROGRAMS {
                    print!("{name} ");
                }
                println!();
                Ok(0)
            }
            FileDescriptor::Stdout if op == SOLAYA_PANIC => {
                panic!("Userspace triggered kernel panic");
            }
            FileDescriptor::UdpSocket(_) | FileDescriptor::UnboundUdpSocket if op == FIONBIO => {
                let arg_ptr = LinuxUserspaceArg::<*const c_int>::new(arg, self.get_process());
                let value = arg_ptr.validate_ptr()?;
                let flags = if value != 0 {
                    FdFlags::from_raw(headers::syscall_types::O_NONBLOCK as i32)
                } else {
                    FdFlags::default()
                };
                self.current_process
                    .with_lock(|p| p.fd_table().set_flags(fd, flags))?;
                Ok(0)
            }
            FileDescriptor::UdpSocket(_) | FileDescriptor::UnboundUdpSocket
                if op == SIOCGIFHWADDR =>
            {
                if !net::has_network_device() {
                    return Err(Errno::ENODEV);
                }
                let ifreq_ptr = LinuxUserspaceArg::<*mut Ifreq>::new(arg, self.get_process());
                let mac = net::current_mac_address();
                let mut result = Ifreq {
                    ifr_name: [0; 16],
                    ifr_data: [0; 16],
                };
                let [lo, hi] = ARPHRD_ETHER.to_le_bytes();
                result.ifr_data[0] = lo;
                result.ifr_data[1] = hi;
                result.ifr_data[2..8].copy_from_slice(&mac.as_bytes());
                ifreq_ptr.write_slice(&[result])?;
                Ok(0)
            }
            FileDescriptor::UdpSocket(_) | FileDescriptor::UnboundUdpSocket
                if op == SIOCSIFADDR =>
            {
                let ifreq_ptr = LinuxUserspaceArg::<*const Ifreq>::new(arg, self.get_process());
                let ifreq = ifreq_ptr.validate_ptr()?;
                let ip = core::net::Ipv4Addr::new(
                    ifreq.ifr_data[4],
                    ifreq.ifr_data[5],
                    ifreq.ifr_data[6],
                    ifreq.ifr_data[7],
                );
                net::set_ip_addr(ip);
                Ok(0)
            }
            _ => Err(Errno::EINVAL),
        }
    }

    async fn writev(
        &mut self,
        fd: c_int,
        iov: LinuxUserspaceArg<*const iovec>,
        iovcnt: c_int,
    ) -> Result<isize, headers::errno::Errno> {
        let descriptor = self
            .current_process
            .with_lock(|p| p.fd_table().get(fd).map(|e| e.descriptor.clone()))
            .ok_or(Errno::EBADF)?;

        let iov = iov.validate_slice(usize::try_from(iovcnt).map_err(|_| Errno::EINVAL)?)?;
        let mut data = Vec::new();

        for io in iov {
            if io.iov_len == 0 {
                continue;
            }
            let buf = LinuxUserspaceArg::<*const u8>::new(io.iov_base as usize, self.get_process());
            let mut buf = buf.validate_slice(io.iov_len.as_usize())?;
            data.append(&mut buf);
        }

        let len = data.len();
        descriptor.write(&data)?;

        Ok(len as isize)
    }

    async fn close(
        &mut self,
        fd: <c_int as crate::syscalls::macros::NeedsUserSpaceWrapper>::Wrapped,
    ) -> Result<isize, headers::errno::Errno> {
        self.current_process.with_lock(|p| p.fd_table().close(fd))?;
        Ok(0)
    }

    async fn dup3(&mut self, oldfd: c_int, newfd: c_int, flags: c_int) -> Result<isize, Errno> {
        let result = self
            .current_process
            .with_lock(|p| p.fd_table().dup_to(oldfd, newfd, flags))?;
        Ok(result as isize)
    }

    async fn pipe2(
        &mut self,
        fds: LinuxUserspaceArg<*mut c_int>,
        _flags: c_int,
    ) -> Result<isize, Errno> {
        let buffer = pipe::new_pipe();
        let (read_fd, write_fd) = self.current_process.with_lock(|p| {
            let r = p
                .fd_table()
                .allocate(FileDescriptor::PipeRead(buffer.clone()))?;
            let w = p.fd_table().allocate(FileDescriptor::PipeWrite(buffer))?;
            Ok::<_, Errno>((r, w))
        })?;
        fds.write_slice(&[read_fd, write_fd])?;
        Ok(0)
    }

    async fn fcntl(
        &mut self,
        fd: c_int,
        cmd: c_int,
        arg: c_ulong,
    ) -> Result<isize, headers::errno::Errno> {
        match cmd.cast_unsigned() {
            F_GETFL => {
                let flags = self
                    .current_process
                    .with_lock(|p| p.fd_table().get_flags(fd))?;
                Ok(flags.as_raw() as isize)
            }
            F_SETFL => {
                let raw = i32::try_from(arg).map_err(|_| Errno::EINVAL)?;
                let flags = FdFlags::from_raw(raw);
                self.current_process
                    .with_lock(|p| p.fd_table().set_flags(fd, flags))?;
                Ok(0)
            }
            _ => Err(Errno::EINVAL),
        }
    }

    async fn fadvise64(
        &mut self,
        _fd: c_int,
        _offset: isize,
        _len: isize,
        _advice: c_int,
    ) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn faccessat(
        &mut self,
        dirfd: c_int,
        pathname: LinuxUserspaceArg<*const u8>,
        _mode: c_int,
    ) -> Result<isize, Errno> {
        let path = self.read_cstring(&pathname)?;
        let _node = if dirfd == headers::fs::AT_FDCWD {
            fs::resolve_path(&path)?
        } else {
            fs::resolve_relative(self.resolve_dirfd_node(dirfd)?, &path)?
        };
        Ok(0)
    }

    async fn fstat(
        &mut self,
        fd: c_int,
        statbuf: LinuxUserspaceArg<*mut u8>,
    ) -> Result<isize, Errno> {
        let file = self
            .current_process
            .with_lock(|p| {
                p.fd_table().get(fd).map(|e| match &e.descriptor {
                    FileDescriptor::VfsFile(f) => Some(f.clone()),
                    _ => None,
                })
            })
            .ok_or(Errno::EBADF)?;

        let st = if let Some(file) = file {
            let node = file.lock().node().clone();
            let mode = match node.node_type() {
                fs::vfs::NodeType::File => headers::fs::S_IFREG | 0o644,
                fs::vfs::NodeType::Directory => headers::fs::S_IFDIR | 0o755,
            };
            headers::fs::stat {
                st_ino: node.ino(),
                st_mode: mode,
                st_nlink: 1,
                st_size: node.size() as i64,
                st_blksize: 4096,
                ..headers::fs::stat::default()
            }
        } else {
            headers::fs::stat {
                st_mode: headers::fs::S_IFCHR | 0o666,
                st_nlink: 1,
                st_blksize: 4096,
                ..headers::fs::stat::default()
            }
        };

        statbuf.write_slice(st.as_slice())?;
        Ok(0)
    }

    async fn futex(
        &mut self,
        uaddr: usize,
        op: c_int,
        val: c_uint,
        _timeout: usize,
        _uaddr2: usize,
        _val3: c_uint,
    ) -> Result<isize, Errno> {
        let cmd = op & !(FUTEX_PRIVATE_FLAG as c_int);
        let main_tid = self.current_process.with_lock(|p| p.main_tid());
        match cmd.cast_unsigned() {
            FUTEX_WAIT => {
                let result =
                    FutexWait::new(self.current_process.clone(), uaddr, val, main_tid).await;
                Ok(result as isize)
            }
            FUTEX_WAKE => {
                let result = futex::futex_wake(main_tid, uaddr, val);
                Ok(result as isize)
            }
            _ => Err(Errno::ENOSYS),
        }
    }

    async fn clock_gettime(
        &mut self,
        _clockid: c_int,
        tp: LinuxUserspaceArg<*mut timespec>,
    ) -> Result<isize, Errno> {
        let ts = timespec {
            tv_sec: 0,
            tv_nsec: 0,
        };
        tp.write_slice(&[ts])?;
        Ok(0)
    }

    async fn llistxattr(
        &mut self,
        _pathname: LinuxUserspaceArg<*const u8>,
        _list: LinuxUserspaceArg<*mut u8>,
        _size: usize,
    ) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn getuid(&mut self) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn geteuid(&mut self) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn getgid(&mut self) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn getegid(&mut self) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn readlinkat(
        &mut self,
        _dirfd: c_int,
        _pathname: LinuxUserspaceArg<*const u8>,
        _buf: LinuxUserspaceArg<*mut u8>,
        _bufsiz: usize,
    ) -> Result<isize, Errno> {
        Err(Errno::EINVAL)
    }

    async fn getpid(&mut self) -> Result<isize, headers::errno::Errno> {
        let main_tid = self.current_process.with_lock(|p| p.main_tid());
        Ok(main_tid.as_isize())
    }

    async fn getppid(&mut self) -> Result<isize, headers::errno::Errno> {
        let parent_tid = self.current_thread.lock().parent_tid();
        Ok(parent_tid.as_isize())
    }

    async fn gettid(&mut self) -> Result<isize, headers::errno::Errno> {
        Ok(self.current_tid.as_isize())
    }

    async fn getpgid(&mut self, pid: c_int) -> Result<isize, Errno> {
        if pid == 0 {
            let pgid = self.current_process.with_lock(|p| p.pgid());
            return Ok(pgid.as_isize());
        }
        let target = Tid::try_from_i32(pid).ok_or(Errno::ESRCH)?;
        let pgid = process_table::THE
            .lock()
            .get_pgid_of(target)
            .ok_or(Errno::ESRCH)?;
        Ok(pgid.as_isize())
    }

    async fn getsid(&mut self, pid: c_int) -> Result<isize, Errno> {
        if pid == 0 {
            let sid = self.current_process.with_lock(|p| p.sid());
            return Ok(sid.as_isize());
        }
        let target = Tid::try_from_i32(pid).ok_or(Errno::ESRCH)?;
        let sid = process_table::THE
            .lock()
            .get_sid_of(target)
            .ok_or(Errno::ESRCH)?;
        Ok(sid.as_isize())
    }

    async fn setpgid(&mut self, pid: c_int, pgid: c_int) -> Result<isize, Errno> {
        let my_main_tid = self.current_process.with_lock(|p| p.main_tid());
        let target_tid = if pid == 0 {
            my_main_tid
        } else {
            Tid::try_from_i32(pid).ok_or(Errno::EINVAL)?
        };
        let new_pgid = if pgid == 0 {
            target_tid
        } else {
            Tid::try_from_i32(pgid).ok_or(Errno::EINVAL)?
        };

        if target_tid != my_main_tid {
            let is_child = process_table::THE
                .lock()
                .is_child_of(my_main_tid, target_tid);
            if !is_child {
                return Err(Errno::ESRCH);
            }
        }

        if !process_table::THE.lock().set_pgid_of(target_tid, new_pgid) {
            return Err(Errno::ESRCH);
        }
        Ok(0)
    }

    async fn setsid(&mut self) -> Result<isize, Errno> {
        self.current_process.with_lock(|mut p| {
            let main_tid = p.main_tid();
            if p.pgid() == main_tid {
                return Err(Errno::EPERM);
            }
            p.set_pgid(main_tid);
            p.set_sid(main_tid);
            Ok(main_tid.as_isize())
        })
    }

    async fn kill(&mut self, pid: c_int, sig: c_int) -> Result<isize, Errno> {
        let sig_u32 = u32::try_from(sig).map_err(|_| Errno::EINVAL)?;
        if sig_u32 >= _NSIG {
            return Err(Errno::EINVAL);
        }
        let target_tid = if pid > 0 {
            Tid::try_from_i32(pid).ok_or(Errno::ESRCH)?
        } else if pid == 0 {
            self.current_process.with_lock(|p| p.main_tid())
        } else {
            return Err(Errno::ESRCH);
        };
        if sig_u32 == 0 {
            return Ok(0);
        }
        process_table::THE
            .lock()
            .send_signal_to_process(target_tid, sig_u32);
        Ok(0)
    }

    async fn tgkill(&mut self, _tgid: c_int, tid: c_int, sig: c_int) -> Result<isize, Errno> {
        let sig_u32 = u32::try_from(sig).map_err(|_| Errno::EINVAL)?;
        if sig_u32 >= _NSIG {
            return Err(Errno::EINVAL);
        }
        let target_tid = Tid::try_from_i32(tid).ok_or(Errno::ESRCH)?;
        if sig_u32 == 0 {
            return Ok(0);
        }
        process_table::THE.lock().send_signal(target_tid, sig_u32);
        Ok(0)
    }

    async fn tkill(&mut self, tid: c_int, sig: c_int) -> Result<isize, Errno> {
        self.tgkill(0, tid, sig).await
    }

    async fn socket(
        &mut self,
        domain: c_int,
        typ: c_int,
        _protocol: c_int,
    ) -> Result<isize, Errno> {
        let masked_type = typ & !SOCK_CLOEXEC;
        assert!(
            domain == AF_INET && masked_type == SOCK_DGRAM,
            "socket: only AF_INET + SOCK_DGRAM supported (got domain={domain}, type={typ:#x})"
        );

        let fd = self
            .current_process
            .with_lock(|p| p.fd_table().allocate(FileDescriptor::UnboundUdpSocket))?;
        Ok(fd as isize)
    }

    async fn bind(
        &mut self,
        fd: c_int,
        addr: LinuxUserspaceArg<*const u8>,
        addrlen: c_uint,
    ) -> Result<isize, Errno> {
        assert!(
            addrlen as usize >= core::mem::size_of::<sockaddr_in>(),
            "bind: addrlen too small ({addrlen})"
        );

        let descriptor = self
            .current_process
            .with_lock(|p| p.fd_table().get(fd).map(|e| e.descriptor.clone()))
            .ok_or(Errno::EBADF)?;

        assert!(
            matches!(descriptor, FileDescriptor::UnboundUdpSocket),
            "bind: fd {fd} is not an unbound UDP socket"
        );

        if !net::has_network_device() {
            return Err(Errno::ENETDOWN);
        }

        let sin_arg =
            LinuxUserspaceArg::<*const sockaddr_in>::new(addr.raw_arg(), self.get_process());
        let sin = sin_arg.validate_ptr()?;
        let port = Port::new(u16::from_be(sin.sin_port));

        let socket = net::open_sockets()
            .lock()
            .try_get_socket(port)
            .ok_or(Errno::EADDRINUSE)?;

        self.current_process.with_lock(|p| {
            p.fd_table()
                .replace_descriptor(fd, FileDescriptor::UdpSocket(socket))
        })?;

        Ok(0)
    }

    async fn sendto(
        &mut self,
        fd: c_int,
        buf: LinuxUserspaceArg<*const u8>,
        len: usize,
        _flags: c_int,
        dest_addr: LinuxUserspaceArg<*const u8>,
        addrlen: c_uint,
    ) -> Result<isize, Errno> {
        assert!(
            addrlen as usize >= core::mem::size_of::<sockaddr_in>(),
            "sendto: addrlen too small ({addrlen})"
        );

        let socket = self
            .current_process
            .with_lock(|p| {
                p.fd_table().get(fd).and_then(|e| match &e.descriptor {
                    FileDescriptor::UdpSocket(s) => Some(s.clone()),
                    _ => None,
                })
            })
            .ok_or(Errno::EBADF)?;

        let data = buf.validate_slice(len)?;
        let sin_arg =
            LinuxUserspaceArg::<*const sockaddr_in>::new(dest_addr.raw_arg(), self.get_process());
        let sin = sin_arg.validate_ptr()?;

        let dest_ip = core::net::Ipv4Addr::from(u32::from_be(sin.sin_addr.s_addr));
        let dest_port = u16::from_be(sin.sin_port);

        if !net::has_network_device() {
            return Err(Errno::ENETDOWN);
        }

        let destination_mac = if dest_ip == core::net::Ipv4Addr::BROADCAST {
            net::mac::MacAddress::new([0xff, 0xff, 0xff, 0xff, 0xff, 0xff])
        } else {
            arp::cache_lookup(&dest_ip).expect("sendto: destination MAC must be in ARP cache")
        };

        let source_port = socket.lock().get_port().as_u16();
        let packet =
            UdpHeader::create_udp_packet(dest_ip, dest_port, destination_mac, source_port, &data);
        net::send_packet(packet);

        Ok(len as isize)
    }

    async fn recvfrom(
        &mut self,
        fd: c_int,
        buf: LinuxUserspaceArg<*mut u8>,
        len: usize,
        _flags: c_int,
        src_addr: LinuxUserspaceArg<Option<*mut u8>>,
        addrlen: LinuxUserspaceArg<Option<*mut c_uint>>,
    ) -> Result<isize, Errno> {
        let (socket, is_nonblocking) = self
            .current_process
            .with_lock(|p| {
                p.fd_table().get(fd).and_then(|e| match &e.descriptor {
                    FileDescriptor::UdpSocket(s) => Some((s.clone(), e.flags.is_nonblocking())),
                    _ => None,
                })
            })
            .ok_or(Errno::EBADF)?;

        let mut tmp_buf = alloc::vec![0u8; len];

        let result = loop {
            let seen = net::sockets::socket_data_counter();
            if let Some(result) = socket.lock().get_datagram(&mut tmp_buf) {
                break result;
            }
            if is_nonblocking {
                return Err(Errno::EAGAIN);
            }
            net::sockets::SocketDataWait::new(seen).await;
        };

        let (bytes_read, from_ip, from_port) = result;
        buf.write_slice(&tmp_buf[..bytes_read])?;

        if src_addr.arg_nonzero() {
            let sin = sockaddr_in {
                sin_family: u16::try_from(AF_INET).expect("AF_INET fits in u16"),
                sin_port: from_port.as_u16().to_be(),
                sin_addr: headers::socket::in_addr {
                    s_addr: u32::from(from_ip).to_be(),
                },
                sin_zero: [0; 8],
            };
            let src_writer =
                LinuxUserspaceArg::<*mut u8>::new(src_addr.raw_arg(), self.get_process());
            src_writer.write_slice(sin.as_slice())?;
            let addrlen_val = c_uint::try_from(core::mem::size_of::<sockaddr_in>())
                .expect("sockaddr_in size fits in c_uint");
            addrlen.write_if_not_none(addrlen_val)?;
        }

        Ok(bytes_read as isize)
    }

    async fn wait4(
        &mut self,
        pid: c_int,
        status: LinuxUserspaceArg<Option<*mut c_int>>,
        options: c_int,
        _rusage: usize,
    ) -> Result<isize, headers::errno::Errno> {
        let wnohang = (options & headers::syscall_types::WNOHANG as c_int) != 0;
        assert!(
            options & !(headers::syscall_types::WNOHANG as c_int) == 0,
            "wait4: unsupported options {options:#x}"
        );

        let parent_main_tid = self.current_thread.lock().get_tid();
        let target = if pid > 0 {
            WaitPid::Specific(Tid::try_from_i32(pid).expect("pid is positive"))
        } else if pid == -1 {
            WaitPid::Any
        } else if pid == 0 {
            let own_pgid = self.current_process.with_lock(|p| p.pgid());
            WaitPid::Pgid(own_pgid)
        } else {
            // pid < -1: wait for any child whose pgid == abs(pid)
            let abs_pid = pid.checked_neg().ok_or(Errno::EINVAL)?;
            WaitPid::Pgid(Tid::try_from_i32(abs_pid).expect("abs(pid) is positive"))
        };
        let (child_tid, wait_status) = WaitChild::new(parent_main_tid, target, wnohang).await?;

        status.write_if_not_none(wait_status)?;

        Ok(child_tid.as_isize())
    }

    async fn clone(
        &mut self,
        flags: c_ulong,
        stack: usize,
        ptid: LinuxUserspaceArg<Option<*mut c_int>>,
        tls: c_ulong,
        ctid: LinuxUserspaceArg<Option<*mut c_int>>,
    ) -> Result<isize, Errno> {
        if (flags & c_ulong::from(CLONE_THREAD)) != 0 {
            self.clone_thread(flags, stack, ptid, tls, ctid)
        } else {
            self.clone_vfork(flags, stack).await
        }
    }

    async fn getcwd(
        &mut self,
        buf: LinuxUserspaceArg<*mut u8>,
        size: usize,
    ) -> Result<isize, Errno> {
        if size < 2 {
            return Err(Errno::ERANGE);
        }
        buf.write_slice(&[b'/', 0])?;
        Ok(2)
    }

    async fn getdents64(
        &mut self,
        fd: c_int,
        dirp: LinuxUserspaceArg<*mut u8>,
        count: usize,
    ) -> Result<isize, Errno> {
        let file = self
            .current_process
            .with_lock(|p| {
                p.fd_table().get(fd).and_then(|e| match &e.descriptor {
                    FileDescriptor::VfsFile(f) => Some(f.clone()),
                    _ => None,
                })
            })
            .ok_or(Errno::EBADF)?;

        let mut inner = file.lock();
        if !inner.is_directory() {
            return Err(Errno::ENOTDIR);
        }

        let entries = inner.node().readdir()?;
        let start_offset = inner.offset();

        let mut out = vec![0u8; count];
        let mut pos = 0usize;
        let mut entry_idx = start_offset;

        for entry in entries.iter().skip(start_offset) {
            let name_bytes = entry.name.as_bytes();
            let name_len = name_bytes.len() + 1; // +1 for null terminator
            let header_size = core::mem::size_of::<headers::fs::linux_dirent64>();
            let reclen = (header_size + name_len + 7) & !7; // align to 8

            if pos + reclen > count {
                break;
            }

            let d_type = match entry.node_type {
                fs::vfs::NodeType::File => headers::fs::DT_REG,
                fs::vfs::NodeType::Directory => headers::fs::DT_DIR,
            };

            entry_idx += 1;

            // Write d_ino
            out[pos..pos + 8].copy_from_slice(&entry.ino.to_le_bytes());
            // Write d_off (next offset)
            out[pos + 8..pos + 16].copy_from_slice(&(entry_idx as i64).to_le_bytes());
            // Write d_reclen
            #[allow(clippy::cast_possible_truncation)]
            let reclen_u16 = reclen as u16;
            out[pos + 16..pos + 18].copy_from_slice(&reclen_u16.to_le_bytes());
            // Write d_type
            out[pos + 18] = d_type;
            // Write d_name
            out[pos + 19..pos + 19 + name_bytes.len()].copy_from_slice(name_bytes);
            out[pos + 19 + name_bytes.len()] = 0;

            pos += reclen;
        }

        inner.seek(entry_idx as isize, headers::fs::SEEK_SET)?;

        if pos > 0 {
            dirp.write_slice(&out[..pos])?;
        }
        Ok(pos as isize)
    }

    async fn lseek(&mut self, fd: c_int, offset: isize, whence: c_int) -> Result<isize, Errno> {
        let file = self
            .current_process
            .with_lock(|p| {
                p.fd_table().get(fd).and_then(|e| match &e.descriptor {
                    FileDescriptor::VfsFile(f) => Some(f.clone()),
                    _ => None,
                })
            })
            .ok_or(Errno::EBADF)?;

        let new_offset = file.lock().seek(offset, whence)?;
        Ok(new_offset as isize)
    }

    async fn mkdirat(
        &mut self,
        dirfd: c_int,
        pathname: LinuxUserspaceArg<*const u8>,
        _mode: c_uint,
    ) -> Result<isize, Errno> {
        if dirfd != headers::fs::AT_FDCWD {
            return Err(Errno::ENOSYS);
        }
        let path = self.read_cstring(&pathname)?;
        let (parent, name) = fs::resolve_parent(&path)?;
        parent.create(name, fs::vfs::NodeType::Directory)?;
        Ok(0)
    }

    async fn newfstatat(
        &mut self,
        dirfd: c_int,
        pathname: LinuxUserspaceArg<*const u8>,
        statbuf: LinuxUserspaceArg<*mut u8>,
        flags: c_int,
    ) -> Result<isize, Errno> {
        let node = if (flags & headers::fs::AT_EMPTY_PATH) != 0 && !pathname.arg_nonzero() {
            let file = self
                .current_process
                .with_lock(|p| {
                    p.fd_table().get(dirfd).and_then(|e| match &e.descriptor {
                        FileDescriptor::VfsFile(f) => Some(f.clone()),
                        _ => None,
                    })
                })
                .ok_or(Errno::EBADF)?;
            file.lock().node().clone()
        } else if dirfd == headers::fs::AT_FDCWD {
            let path = self.read_cstring(&pathname)?;
            fs::resolve_path(&path)?
        } else {
            let path = self.read_cstring(&pathname)?;
            fs::resolve_relative(self.resolve_dirfd_node(dirfd)?, &path)?
        };

        let mode = match node.node_type() {
            fs::vfs::NodeType::File => headers::fs::S_IFREG | 0o644,
            fs::vfs::NodeType::Directory => headers::fs::S_IFDIR | 0o755,
        };

        let st = headers::fs::stat {
            st_ino: node.ino(),
            st_mode: mode,
            st_nlink: 1,
            st_size: node.size() as i64,
            st_blksize: 4096,
            ..headers::fs::stat::default()
        };

        statbuf.write_slice(st.as_slice())?;
        Ok(0)
    }

    async fn statx(
        &mut self,
        dirfd: c_int,
        pathname: LinuxUserspaceArg<*const u8>,
        flags: c_int,
        _mask: c_uint,
        statxbuf: LinuxUserspaceArg<*mut u8>,
    ) -> Result<isize, Errno> {
        let node = if (flags & headers::fs::AT_EMPTY_PATH) != 0 && !pathname.arg_nonzero() {
            let file = self
                .current_process
                .with_lock(|p| {
                    p.fd_table().get(dirfd).and_then(|e| match &e.descriptor {
                        FileDescriptor::VfsFile(f) => Some(f.clone()),
                        _ => None,
                    })
                })
                .ok_or(Errno::EBADF)?;
            file.lock().node().clone()
        } else if dirfd == headers::fs::AT_FDCWD {
            let path = self.read_cstring(&pathname)?;
            fs::resolve_path(&path)?
        } else {
            let path = self.read_cstring(&pathname)?;
            fs::resolve_relative(self.resolve_dirfd_node(dirfd)?, &path)?
        };

        #[allow(clippy::cast_possible_truncation)]
        let mode: u16 = match node.node_type() {
            fs::vfs::NodeType::File => (headers::fs::S_IFREG | 0o644) as u16,
            fs::vfs::NodeType::Directory => (headers::fs::S_IFDIR | 0o755) as u16,
        };

        let st = headers::fs::statx {
            stx_mask: 0x7ff,
            stx_blksize: 4096,
            stx_nlink: 1,
            stx_mode: mode,
            stx_ino: node.ino(),
            stx_size: node.size() as u64,
            ..headers::fs::statx::default()
        };

        statxbuf.write_slice(st.as_slice())?;
        Ok(0)
    }

    async fn openat(
        &mut self,
        dirfd: c_int,
        pathname: LinuxUserspaceArg<*const u8>,
        flags: c_int,
        _mode: c_uint,
    ) -> Result<isize, Errno> {
        if dirfd != headers::fs::AT_FDCWD {
            return Err(Errno::ENOSYS);
        }
        let path = self.read_cstring(&pathname)?;
        let flags_u32 = flags.cast_unsigned();

        let node = match fs::resolve_path(&path) {
            Ok(n) => {
                if (flags_u32 & O_TRUNC) != 0 {
                    n.truncate()?;
                }
                n
            }
            Err(Errno::ENOENT) if (flags_u32 & O_CREAT) != 0 => {
                let (parent, name) = fs::resolve_parent(&path)?;
                parent.create(name, fs::vfs::NodeType::File)?
            }
            Err(e) => return Err(e),
        };

        if (flags_u32 & O_DIRECTORY) != 0 && node.node_type() != fs::vfs::NodeType::Directory {
            return Err(Errno::ENOTDIR);
        }

        let open_file = fs::open_file::open(node, flags);
        let fd = self
            .current_process
            .with_lock(|p| p.fd_table().allocate(FileDescriptor::VfsFile(open_file)))?;
        Ok(fd as isize)
    }

    async fn umask(&mut self, mask: c_uint) -> Result<isize, Errno> {
        let old = self.current_process.with_lock(|mut p| {
            let old = p.umask();
            p.set_umask(mask & 0o777);
            old
        });
        Ok(old as isize)
    }

    async fn unlinkat(
        &mut self,
        dirfd: c_int,
        pathname: LinuxUserspaceArg<*const u8>,
        flags: c_int,
    ) -> Result<isize, Errno> {
        if dirfd != headers::fs::AT_FDCWD {
            return Err(Errno::ENOSYS);
        }
        let path = self.read_cstring(&pathname)?;
        let (parent, name) = fs::resolve_parent(&path)?;

        if (flags & headers::fs::AT_REMOVEDIR) != 0 {
            let node = parent.lookup(name)?;
            if node.node_type() != fs::vfs::NodeType::Directory {
                return Err(Errno::ENOTDIR);
            }
            if !node.readdir()?.is_empty() {
                return Err(Errno::ENOTEMPTY);
            }
        } else {
            let node = parent.lookup(name)?;
            if node.node_type() == fs::vfs::NodeType::Directory {
                return Err(Errno::EISDIR);
            }
        }

        parent.unlink(name)?;
        Ok(0)
    }

    async fn utimensat(
        &mut self,
        _dirfd: c_int,
        _pathname: LinuxUserspaceArg<*const u8>,
        _times: usize,
        _flags: c_int,
    ) -> Result<isize, Errno> {
        Ok(0)
    }

    async fn execve(&mut self, filename: usize, argv: usize, _envp: usize) -> Result<isize, Errno> {
        let process = self.get_process();
        let filename_bytes = process.with_lock(|p| {
            let ptr = UserspacePtr::new(filename as *const u8);
            p.read_userspace_slice(&ptr, 256)
        })?;
        let mut buf = ConsumableBuffer::new(&filename_bytes);
        let filename_str = buf.consume_str().ok_or(Errno::EFAULT)?;
        let name = filename_str.strip_prefix('/').unwrap_or(filename_str);

        // Read argv
        let mut args: Vec<&str> = Vec::new();
        let argv_ptrs = process.with_lock(|p| {
            let ptr = UserspacePtr::new(argv as *const usize);
            p.read_userspace_slice(&ptr, 32)
        })?;

        // Skip argv[0] (program name) since load_elf adds it automatically
        let mut arg_buffers: Vec<Vec<u8>> = Vec::new();
        let mut first = true;
        for &arg_ptr in &argv_ptrs {
            if arg_ptr == 0 {
                break;
            }
            if first {
                first = false;
                continue;
            }
            let arg_bytes = process.with_lock(|p| {
                let ptr = UserspacePtr::new(arg_ptr as *const u8);
                p.read_userspace_slice(&ptr, 256)
            })?;
            arg_buffers.push(arg_bytes);
        }
        for buf_ref in &arg_buffers {
            let mut cb = ConsumableBuffer::new(buf_ref);
            if let Some(s) = cb.consume_str() {
                args.push(s);
            }
        }

        let elf_data = PROGRAMS
            .iter()
            .find(|(prog_name, _)| *prog_name == name)
            .map(|(_, data)| *data)
            .ok_or(Errno::ENOENT)?;

        let elf = ElfFile::parse(elf_data).expect("Cannot parse ELF file");
        let loaded = loader::load_elf(&elf, name, &args).expect("ELF loading must succeed");

        let process_name = Arc::new(String::from(name));
        let old_process = self.get_process();
        let (old_pgid, old_sid) = old_process.with_lock(|p| (p.pgid(), p.sid()));
        let new_process = Arc::new(crate::klibc::Spinlock::new(Process::new(
            process_name.clone(),
            loaded.page_tables,
            loaded.allocated_pages,
            loaded.brk,
            self.current_thread.lock().get_tid(),
            old_pgid,
            old_sid,
        )));

        let mut inherited_fd_table = self.get_process().with_lock(|p| p.fd_table().clone());
        inherited_fd_table.close_cloexec_fds();
        new_process.lock().set_fd_table(inherited_fd_table);

        let current_thread = self.current_thread.clone();
        let old_process = current_thread.lock().process();
        let tid = current_thread.lock().get_tid();

        old_process.lock().remove_thread(tid);

        current_thread.with_lock(|mut t| {
            t.set_process(new_process.clone(), process_name);
            let mut regs = TrapFrame::zero();
            regs[Register::a0] = loaded.args_start.as_usize();
            regs[Register::sp] = loaded.args_start.as_usize();
            t.set_register_state(regs);
            t.set_program_counter(loaded.entry_address);
            t.set_registers_replaced(true);

            if let Some(vfork_state) = t.take_vfork_state() {
                vfork_state.lock().wake();
            }
        });

        new_process
            .lock()
            .add_thread(tid, Arc::downgrade(&current_thread));

        Ok(0)
    }
}

impl LinuxSyscallHandler {
    pub fn new() -> Self {
        let current_thread = Cpu::with_scheduler(|s| s.get_current_thread().clone());
        let (current_tid, current_process) =
            current_thread.with_lock(|t| (t.get_tid(), t.process()));
        Self {
            current_process,
            current_thread,
            current_tid,
        }
    }

    fn resolve_dirfd_node(&self, dirfd: c_int) -> Result<fs::vfs::VfsNodeRef, Errno> {
        self.current_process
            .with_lock(|p| {
                p.fd_table().get(dirfd).and_then(|e| match &e.descriptor {
                    FileDescriptor::VfsFile(f) => Some(f.lock().node().clone()),
                    _ => None,
                })
            })
            .ok_or(Errno::EBADF)
    }

    async fn clone_vfork(&mut self, flags: c_ulong, stack: usize) -> Result<isize, Errno> {
        let expected = c_ulong::from(CLONE_VM | CLONE_VFORK | SIGCHLD);
        assert!(
            flags == expected,
            "clone_vfork: unsupported flags {flags:#x}, expected {expected:#x}"
        );

        let parent_regs = Cpu::read_trap_frame();
        let parent_pc = arch::cpu::read_sepc();

        let parent_process = self.current_process.clone();
        let (parent_main_tid, child_name, parent_pgid, parent_sid) =
            parent_process.with_lock(|p| {
                (
                    p.main_tid(),
                    Arc::new(String::from(p.get_name())),
                    p.pgid(),
                    p.sid(),
                )
            });

        let vfork_state = VforkState::new();
        let child_tid = get_next_tid();

        let child_page_table =
            crate::memory::page_tables::RootPageTableHolder::new_with_kernel_mapping(false);
        let child_process = Arc::new(crate::klibc::Spinlock::new(Process::new(
            child_name.clone(),
            child_page_table,
            Vec::new(),
            Brk::empty(),
            child_tid,
            parent_pgid,
            parent_sid,
        )));
        child_process
            .lock()
            .set_vfork_parent(parent_process.clone());

        let parent_fd_table = parent_process.with_lock(|p| p.fd_table().clone());
        child_process.lock().set_fd_table(parent_fd_table);

        let mut child_regs = parent_regs;
        child_regs[Register::a0] = 0;
        if stack != 0 {
            child_regs[Register::sp] = stack;
        }

        let child_thread = Thread::new(
            child_tid,
            child_name,
            child_regs,
            VirtAddr::new(parent_pc + 4),
            false,
            child_process.clone(),
            parent_main_tid,
        );

        child_thread.lock().set_vfork_state(vfork_state.clone());

        child_process
            .lock()
            .add_thread(child_tid, Arc::downgrade(&child_thread));
        process_table::THE.lock().add_thread(child_thread);

        VforkWait::new(vfork_state).await;

        Ok(child_tid.as_isize())
    }

    fn clone_thread(
        &mut self,
        flags: c_ulong,
        stack: usize,
        ptid: LinuxUserspaceArg<Option<*mut c_int>>,
        tls: c_ulong,
        ctid: LinuxUserspaceArg<Option<*mut c_int>>,
    ) -> Result<isize, Errno> {
        let parent_regs = Cpu::read_trap_frame();
        let parent_pc = arch::cpu::read_sepc();

        let parent_process = self.current_process.clone();
        let (parent_main_tid, child_name) =
            parent_process.with_lock(|p| (p.main_tid(), Arc::new(String::from(p.get_name()))));

        let child_tid = get_next_tid();

        let mut child_regs = parent_regs;
        child_regs[Register::a0] = 0;
        if stack != 0 {
            child_regs[Register::sp] = stack;
        }
        if (flags & c_ulong::from(CLONE_SETTLS)) != 0 {
            child_regs[Register::tp] = usize::try_from(tls).expect("tls fits in usize");
        }

        let child_thread = Thread::new(
            child_tid,
            child_name,
            child_regs,
            VirtAddr::new(parent_pc + 4),
            false,
            parent_process.clone(),
            parent_main_tid,
        );

        if (flags & c_ulong::from(CLONE_CHILD_CLEARTID)) != 0 {
            child_thread.lock().set_clear_child_tid((&ctid).into());
        }

        parent_process.with_lock(|mut p| {
            p.add_thread(child_tid, Arc::downgrade(&child_thread));
        });

        if (flags & c_ulong::from(CLONE_PARENT_SETTID)) != 0 {
            ptid.write_if_not_none(
                c_int::try_from(child_tid.as_isize()).expect("tid fits in c_int"),
            )?;
        }

        process_table::THE.lock().add_thread(child_thread);

        Ok(child_tid.as_isize())
    }

    fn read_cstring(&self, arg: &LinuxUserspaceArg<*const u8>) -> Result<String, Errno> {
        let addr = arg.raw_arg();
        let max_len = 256usize.min(usize::MAX - addr + 1);
        let bytes = arg.validate_slice(max_len)?;
        let mut buf = ConsumableBuffer::new(&bytes);
        let s = buf.consume_str().ok_or(Errno::EFAULT)?;
        Ok(String::from(s))
    }

    fn validate_poll_timeout(to: Option<timespec>) {
        if let Some(to) = to {
            assert_eq!(to.tv_sec, 0, "ppoll with timeout not yet implemented");
            assert_eq!(to.tv_nsec, 0, "ppoll with timeout not yet implemented");
        }
    }
}
