name: warmup
runs:
  using: "composite"
  steps:     
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock', 'rust-toolchain') }}
        restore-prefixes-all-matches: nix-${{ runner.os }}-
    - uses: nicknovitski/nix-develop@v1
