use std::{collections::BTreeMap, env, error::Error, fs::read_dir, io::Write, process::Command};

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=qemu.ld");
    println!("cargo:rerun-if-changed=../userspace/");
    println!("cargo:rerun-if-changed=../common/");
    println!("cargo:rerun-if-changed=../flake.nix");
    println!("cargo:rerun-if-changed=../flake.lock");
    println!("cargo:rustc-link-arg-bin=kernel=-Tkernel/qemu.ld");

    if is_miri_execution() {
        return Ok(());
    }

    generate_userspace_programs_include()?;

    Ok(())
}

fn is_miri_execution() -> bool {
    env::var_os("CARGO_CFG_MIRI").is_some()
}

fn generate_userspace_programs_include() -> Result<(), Box<dyn Error>> {
    const USERSPACE_PROGRAMS_PATH: &str = "../kernel/src/autogenerated/userspace_programs.rs";

    let mut userspace_programs = std::fs::File::create(USERSPACE_PROGRAMS_PATH)?;

    writeln!(userspace_programs, "use common::include_bytes_align_as;\n")?;

    // Use BTreeMap to have the program names in a sorted order
    let mut programs: BTreeMap<String, String> = BTreeMap::new();

    let compiled_userspace = read_dir("../kernel/compiled_userspace")?;
    let compiled_userspace_nix = read_dir("../kernel/compiled_userspace_nix")?;

    let entries = compiled_userspace.chain(compiled_userspace_nix);

    for entry in entries {
        let entry = entry?;
        let path = entry.path();
        let absolute_path = std::fs::canonicalize(&path)?;
        let original_file_name = path.file_name().unwrap().to_str().unwrap();
        let file_name = original_file_name.to_uppercase().replace('-', "_");

        programs.insert(original_file_name.to_owned(), file_name.clone());

        writeln!(
            userspace_programs,
            "pub static {file_name}: &[u8] = include_bytes_align_as!(u64, \"{}\");",
            absolute_path.to_string_lossy()
        )?;
    }

    writeln!(userspace_programs)?;
    write!(
        userspace_programs,
        "pub static PROGRAMS: &[(&str, &[u8])] = &["
    )?;
    for (original_file_name, file_name) in programs {
        write!(
            userspace_programs,
            "(\"{original_file_name}\", {file_name}),"
        )?;
    }

    write!(userspace_programs, "];")?;

    drop(userspace_programs);

    // Format the newly generated file
    Command::new("cargo")
        .arg("fmt")
        .arg("--")
        .arg(USERSPACE_PROGRAMS_PATH)
        .spawn()?
        .wait()?;

    Ok(())
}
