[build]
target = "riscv64gc-unknown-none-elf"
# Leave it here in case we need it in the future
# Or just if we forget and get here by accident to remember
# rustflags = ["-Ctarget-feature=+relax"]

[target.riscv64gc-unknown-none-elf]
runner = """
qemu-system-riscv64 \
    -machine virt \
    -cpu rv64 \
    -smp 1 \
    -m 128M \
    -nographic \
    -serial mon:stdio \
    -d guest_errors,cpu_reset,unimp \
    -netdev user,id=netdev1,hostfwd=udp::1234-:1234 -device virtio-net-pci,netdev=netdev1 \
    -kernel 
"""
# This can be used to capture network traffic
# -object filter-dump,id=f1,netdev=netdev1,file=network.pcap \
