name: prepare
runs:
  using: "composite"
  steps:     
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        gc-max-store-size-linux: 1G
    - uses: nicknovitski/nix-develop@v1
