name: prepare
runs:
  using: "composite"
  steps:     
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: ".#ci"
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cache/miri
          target/
        key: ${{ runner.os }}-miri-${{ hashFiles('**/Cargo.lock', 'rust-toolchain') }}
