name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@just
    - name: Install clippy
      run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
    - uses: actions/checkout@v3
    - name: Build
      run: just build-release
    - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: qemu-system-riscv64
          version: 14082023
    - name: Run tests
      run: just test
