name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v3
      - name: Install clippy
        run: rustup component add clippy
      - name: Clippy
        run: just clippy

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v3
      - name: Build
        run: just build-release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install qemu-system-riscv64
      - name: Run tests
        run: just test

  miri:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v3
      - name: Install miri
        run: rustup component add miri
      - name: Run miri
        run: just miri
