name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@just
    - uses: actions/checkout@v3
    - name: Build
      run: just build-release
    - name: Install dependencies
      run: sudo apt update && sudo apt install qemu-system-riscv64
    - name: Run tests
      run: just test
