name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
      - name: Install clippy
        run: rustup component add clippy
      - name: Clippy
        run: just clippy

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
      - name: Build
        run: just build
