name: clean

on:
  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  clean:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v6
        with:
          clean: false
      - uses: ./.github/actions/setup
      - run: just clean
