name: Test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-system-riscv64 binutils-multiarch
      - name: Run tests
        run: just test
      - name: Install miri
        run: rustup component add miri
      - name: Run miri
        run: just miri
