name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@just
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install qemu-system-riscv64
      - name: Run tests
        run: just test
